trigger:
  branches:
    include:
      - main

stages:
- stage: Deploy
  jobs:
  - job: DeployToS3
    pool:
      vmImage: ubuntu-latest
    steps:
    # Install Node.js
    - task: NodeTool@0
      inputs:
        versionSpec: '24.x'
      displayName: 'Install Node.js'

    # Install Angular and build project
    - task: CmdLine@2
      displayName: 'Install dependencies and build Angular app'
      inputs:
        script: |
          npm install -g @angular/cli
          npm install
          ng build --configuration production

    # # **AWS CLI Install**
    # - script: |
    #     sudo apt-get update
    #     sudo apt-get install -y awscli
    #   displayName: 'Install AWS CLI'

    # **Clear S3 Bucket**
    - task: AWSCLI@1
      inputs:
        awsCredentials: 'aws-s3-connection'
        regionName: 'us-east-1'
        command: 's3 rm'
        arguments: 's3://test.bd-book.com --recursive'
      displayName: 'Clear S3 Bucket'

    # **Upload dist folder**
    - task: S3Upload@1
      inputs:
        awsCredentials: 'aws-s3-connection'
        regionName: 'us-east-1'
        bucketName: 'test.bd-book.com'
        sourceFolder: 'dist'
        globExpressions: '**'
        createBucket: false
        logRequest: true
        logResponse: true
      displayName: 'Upload dist folder to S3'