trigger:
 branches:
  include:
   - main
pool:
 vmImage: ubuntu-latest
stages:
 - stage: BuildAndDeploy
   displayName: Build Angular and Deploy to S3
   jobs:
    - job: Build
      displayName: Build and Upload Angular App
      steps:
       - task: NodeTool@0
         inputs:
          versionSpec: 24.x
         displayName: Install Node.js
       - script: |
          npm install -g @angular/cli
          npm ci
          ng build --configuration production
         displayName: Install & Build Angular App
       - task: UsePythonVersion@0
         inputs:
          versionSpec: 3.x
         displayName: Use Python 3
       - script: |
          pip install --upgrade pip
          pip install awscli --upgrade
         displayName: Install AWS CLI via pip
       - task: AWSCLI@1
         displayName: Clear S3 Bucket
         inputs:
          awsCredentials: aws-s3-connection
          regionName: us-east-1
          awsCommand: s3
          awsSubCommand: 'rm'
          awsArguments: 's3://test.bd-book.com --recursive'
          logRequest: true
          logResponse: true
       - task: S3Upload@1
         displayName: Upload dist folder to S3
         inputs:
          awsCredentials: aws-s3-connection
          regionName: us-east-1
          bucketName: test.bd-book.com
          sourceFolder: dist/test1
          globExpressions: "**/*"
          targetFolder: ""
          createBucket: false
          logRequest: true
          logResponse: true
