variables:
  buildConfiguration: production
  buildPlatform: Any CPU
  nodeVersion: '24.x'


  solution: '**/*.sln'
  projectPath: 'WebApplication1/WebApplication1.csproj'
  RestoreBuildProjects: '**/*.csproj'
  appName: 'WebApplication1'

  azureServiceConnection: ''
  webAppName: ''
  iisSiteName: ''    
  
  # Use pipeline variables; mark sensitive ones as secret in DevOps
  SourcePath: 'a\Books.Web.Api'
  ServiceUrl: 'https://win1032.site4now.net:8172/msdeploy.axd?site=saidul1983-001-site1'
  SiteName: 'saidul1983-001-site1'
  UserName: 'saidul1983-001'        
  Password: 'mislam1983'    
