variables:
  buildConfiguration: production
  buildPlatform: Any CPU
  nodeVersion: '24.x'

  awsCredentials: 'aws-s3-connection'
  regionName: 'us-east-1'
  bucketName: 'beta.bd-book.com'
  sourceFolder: 'dist/test1/browser'    
