jobs:
  - job: BuildWithPublishBuildArtifacts
    pool:
      vmImage: 'ubuntu-latest'
    steps:      
      - template: ../steps/build.yml
      # - template: ../steps/publish-build-artifacts.yml
      # - template: ../steps/deploy-hostbudy.yml
