jobs:
  - deployment: DeployIIS
    environment: production
    pool:
      vmImage: 'windows-latest'
    strategy:
      runOnce:
        deploy:
          steps:
            - template: ../steps/deploy-iis.yml
