steps:
  - task: NodeTool@0
    inputs:
      versionSpec: 24.x
    displayName: Install Node.js
  - script: |
     npm install -g @angular/cli
     npm ci
     ng build --configuration production
    displayName: Install & Build Angular App

