steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '$(nodeVersion)'
    displayName: Install Node.js
  - script: |
     npm install -g @angular/cli
     npm ci
     ng build --configuration $(buildConfiguration)
    displayName: Install & Build Angular App

