steps:
 - task: AWSCLI@1
   displayName: Clear S3 Bucket
   inputs:
    awsCredentials: aws-s3-connection
    regionName: us-east-1
    awsCommand: s3
    awsSubCommand: 'rm'
    awsArguments: 's3://beta.bd-book.com --recursive'
    logRequest: true
    logResponse: true
 - task: S3Upload@1
   displayName: Upload dist folder to S3
   inputs:
    awsCredentials: aws-s3-connection
    regionName: us-east-1
    bucketName: beta.bd-book.com
    sourceFolder: dist/test1/browser
    globExpressions: "**/*"
    targetFolder: ""
    createBucket: false
    logRequest: true
    logResponse: true
